### ISSUE TITLE
deployed does not work

### ISSUE THREAD

**Issue by quickstreamingmedia** [AgoraIO/OpenAgoraWeb-React#3]
https://blazeinmedia.github.io/test/index.html

**Comment by menthays** [comment]
GET https://blazeinmedia.github.io/test/test/static/js/main.b9368184.js net::ERR_ABORTED
It seems like path of your static file were wrong. We use create-react-app as scaffolds, you can write your deploy path (for example, here is 'https://blazeinmedia.github.io/test/') or '.' to param 'homepage' in package.json to make public path right.
