### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by kjaspreet** [AgoraIO/OpenAgoraWeb-React#4]
When I run this App locally and tried to make the video call then I am getting this error:
index.js:2177 00:37:03:873 ERROR: Media access: NotReadableError
__stack_frame_overlay_proxy_console__ @ index.js:2177
t @ AgoraRTCSDK-2.1.0.js:1
a @ AgoraRTCSDK-2.1.0.js:1
(anonymous) @ AgoraRTCSDK-2.1.0.js:1
index.jsx:59 getUserMedia failed {type: "error", msg: "NotReadableError"}

and when I deployed this app on Heroku and tried to make the video call then I am getting following error:

00:34:12:435 ERROR: Media access: NotReadableError
__stack_frame_overlay_proxy_console__ @ index.js:2177

**Comment by menthays** [comment]
It seems that webcam is allowed but not possible. Maybe it is being occupied or there was a hareware error. Check [this](https://stackoverflow.com/questions/42568498/notreadableerror-failed-to-allocate-videosource) for more info.

**Comment by kjaspreet** [comment]
thank you very much. Today, I tried it on chrome and it's working. Earlier I was using firefox.
